import Footer from "../_components/Footer";
import UserBootstrap from "../_components/auth/UserBootstrap";
import SessionRefresh from "../_components/auth/SessionRefresh";

export const metadata = {
  title: "DevFlow | Your Web based code editor",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <main className="flex-1">
        <SessionRefresh />
        <UserBootstrap />
        {children}
      </main>
      <Footer />
    </div>
  );
}
